// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7UVA69NDJZQUtQe53ntcU2uAMkQBPCX0',
    appId: '1:777427744597:web:d5a09d341ec8289dc0e1dc',
    messagingSenderId: '777427744597',
    projectId: 'job-dream',
    authDomain: 'job-dream.firebaseapp.com',
    storageBucket: 'job-dream.appspot.com',
    measurementId: 'G-QVL3J5HPZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6VTX4O39wWswkHzmQuADwk3z3DvcR-Q',
    appId: '1:777427744597:android:e077f410454ea68cc0e1dc',
    messagingSenderId: '777427744597',
    projectId: 'job-dream',
    storageBucket: 'job-dream.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodphGq5Dof5MNbbyUKP_gIxEXv-k6WbE',
    appId: '1:777427744597:ios:ca8fce6a7c1427a6c0e1dc',
    messagingSenderId: '777427744597',
    projectId: 'job-dream',
    storageBucket: 'job-dream.appspot.com',
    iosBundleId: 'com.example.jobDream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodphGq5Dof5MNbbyUKP_gIxEXv-k6WbE',
    appId: '1:777427744597:ios:b515b18c48d1159cc0e1dc',
    messagingSenderId: '777427744597',
    projectId: 'job-dream',
    storageBucket: 'job-dream.appspot.com',
    iosBundleId: 'com.example.jobDream.RunnerTests',
  );
}
